Support for next 13.5
scottrippey/next-router-mock pull request #105
Opened 2023-09-20 15:08 UTC by jantimon

Next 13.5 renamed a file.

This pr adds:

 - support for 13.5
 - tests for 13.5

2023-09-20 15:47 UTC, scottrippey commented on package.json
> +    "test:integration": "npm run build && npm run test:exports && npm run test:example-app && npm run test:next-10 && npm run test:next-11 && npm run test:next-12 && npm run test:next-12.2 && npm run
```suggestion
    "test:integration": "npm run build && npm run test:exports && npm run test:example-app && npm run test:next-10 && npm run test:next-11 && npm run test:next-12 && npm run test:next-12.2 && npm run test:next-12.latest && npm run test:next-13 && npm run test:next-13.5",
```

2023-09-20 15:54 UTC, scottrippey requested changes
Fantastic work, thank you for copying the existing patterns so well!

ToDo:
- [ ] Add `/MemoryRouterProvider/next-13.5/package.json` entrypoint
- [ ] Make updates listed below
- [ ] Update `README.md` with instructions
- [x] Complain to Next.js that they keep making it hard to test `next/router` and `next/link` because they keep moving these files around (done: https://github.com/vercel/next.js/discussions/38248)

2023-09-20 15:54 UTC, scottrippey commented on src/MemoryRouterProvider/next-11.tsx
>  // NOTE: this path works with Next v11.1.0+
```suggestion
// NOTE: this path works with Next v11.1.0 through v13.4.0+
```

2023-09-20 15:54 UTC, scottrippey commented on test/next-13.5/next-13.5.test.ts
> +import type { MemoryRouterProvider as __ } from "../../MemoryRouterProvider/next-13";
We'll need to create another entry-point here too:

```suggestion
import type { MemoryRouterProvider as __ } from "../../MemoryRouterProvider/next-13.5";
```

2023-09-20 15:54 UTC, scottrippey commented on test/next-13.5/next-13.5.test.ts
> +      require("../../MemoryRouterProvider/next-13");
```suggestion
      require("../../MemoryRouterProvider/next-13.5");
```

2023-09-20 21:52 UTC, scottrippey commented on .changeset/hot-bears-bake.md
> +Add support for Next 13.5
Updated `MemoryRouterProvider` to support Next 13.5

2023-09-20 22:48 UTC, scottrippey approved these changes

2023-09-21 05:45 UTC, jantimon commented
nice work! :)

2023-09-21 11:13 UTC, PizzaPete approved these changes

2023-09-22 10:03 UTC, gmerwan approved these changes
Great ✅ .. looking forward to the update 🙏🏻

2023-09-25 14:33 UTC, merged